---
title: 'Debezium & MySQL v8 : Public Key Retrieval Is Not Allowed'
date: "2019-10-23T11:54:51-04:00"
description: ""
tldr: ""
image: "/images/2019/04/IMG_3685.JPG"
credit: ""
thumbnail: "/images/2019/04/IMG_9090.jpg"
categories:
- Debezium
- MySQL
---

I started hitting problems when trying Debezium against MySQL v8. When creating the connector: 

<!--more-->

{{< highlight shell >}}
curl -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/source-debezium-mysql-00/config \
    -d '{
          "connector.class": "io.debezium.connector.mysql.MySqlConnector",
          "database.hostname": "mysql",
          "database.port": "3306",
          "database.user": "debezium",
          "database.password": "dbz",
          "database.server.id": "42",
          "database.server.name": "asgard",
          "table.whitelist": "demo.customers",
          "database.history.kafka.bootstrap.servers": "kafka:29092",
          "database.history.kafka.topic": "asgard.dbhistory.demo" ,
          "include.schema.changes": "true"
    }'
{{< /highlight >}}

I'd get the error

{{< highlight json >}}
{
    "error_code": 400,
    "message": "Connector configuration is invalid and contains the following 1 error(s):\nUnable to connect: Public Key Retrieval is not allowed\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
}
{{< /highlight >}}

The fix for this, courtesy of Jiri on the https://gitter.im/debezium/user[Debezium gitter.im chat room], is to add to the connector configuraton `database.allowPublicKeyRetrieval=true`: 

{{< highlight shell >}}
curl -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/source-debezium-mysql-00/config \
    -d '{
          "connector.class": "io.debezium.connector.mysql.MySqlConnector",
          "database.hostname": "mysql",
          "database.port": "3306",
          "database.user": "debezium",
          "database.password": "dbz",
          "database.server.id": "42",
          "database.allowPublicKeyRetrieval":"true",
          "database.server.name": "asgard",
          "table.whitelist": "demo.customers",
          "database.history.kafka.bootstrap.servers": "kafka:29092",
          "database.history.kafka.topic": "asgard.dbhistory.demo" ,
          "include.schema.changes": "true"
    }'
{{< /highlight >}}

After this the connector was created successfully, but immediately `FAILED` with the following error in the Kafka Connect worker log: 

{{< highlight shell >}} 
org.apache.kafka.connect.errors.ConnectException: Failed to authenticate to the MySQL database at mysql:3306 with user 'debezium'
[‚Ä¶]
com.github.shyiko.mysql.binlog.network.AuthenticationException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
{{< /highlight >}}

A bit of Googling threw up https://github.com/shyiko/mysql-binlog-connector-java/issues/240[this issue on GitHub] with a solution that worked‚Äîadd `WITH mysql_native_password` to the authentication settings for the Debezium user: 

{{< highlight sql >}}
ALTER USER 'debezium'@'%' IDENTIFIED WITH mysql_native_password BY 'dbz';
{{< /highlight >}}

After that, the connector ran successfully üëç 